### DISCUSSION TITLE
Setup mirror for docker/setup-buildx-action

### DISCUSSION THREAD

**Discussion by flyoozes** [docker/setup-buildx-action#352] [Q&A]
Hello! 
I was trying to setup mirror for buildx because our github runner doesn't have access to public docker hub registry. 
```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["https://art.test.com/artifactory/hub-docker-com"]
```
but whenever it's setting up builder it is failing with

`#1 ERROR: Error response from daemon: Get "https://registry-1.docker.io/v2/": http: server gave HTTP response to HTTPS client`

shouldn't it go to mirror and how to setup it correctly?
