### ISSUE TITLE
Configure to use existing buildx builders on Kubernetes cluster?

### ISSUE THREAD

**Issue by abatilo** [docker/setup-buildx-action#111]
If I were to configure a pool of buildx agents on a Kubernetes cluster ahead of time, is there a way to basically tell this action to use those instead of creating new pods? This way I could leverage the caches on nodes.

**Comment by ddelange** [comment]
+1! I'm guessing this is a duplicate of https://github.com/docker/buildx/issues/23

**Comment by pl4nty** [comment]
This is now available via the `remote` driver

```yaml
- uses: docker/setup-buildx-action@v3.0.0
  with:
    driver: remote
    endpoint: tcp://buildkitd.tplant.com.au:1234
  env:
    BUILDER_NODE_0_AUTH_TLS_CACERT: ${{ secrets.BUILDKIT_ARM_CA }}
    BUILDER_NODE_0_AUTH_TLS_CERT: ${{ secrets.BUILDKIT_ARM_CERT }}
    BUILDER_NODE_0_AUTH_TLS_KEY: ${{ secrets.BUILDKIT_ARM_KEY }}
```
