### ISSUE TITLE
"tag does not exist" trying to push after specifying multiple tags and a target with buildx

### ISSUE THREAD

**Issue by humphd** [docker/setup-buildx-action#116]
This may not have anything to do with docker/setup-buildx-action, but it's odd, so I wanted to report it.

I have a workflow that, among other things, does this (NOTE: I've changed the user/repo to just `name`):

```yml
      - name: Docker Build and Tag
        run: docker build -t name:latest -t name:$GITHUB_SHA --target deploy .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push Docker image tags to Docker Hub
        run: |
          docker push name:latest
          docker push name:$GITHUB_SHA
```

It's using multiple tags and also a target.  This has been working great.  However, today I added `buildx` to my workflow so I could skip building stages that aren't needed by my target.  I added the following:

```yml
      # Use buildx, which is faster and can optimize the build steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
```

This does indeed cause `docker build` to use buildx, and the build is much faster.  But when it tries to push the tags, it encounters the following error:

```
The push refers to repository [docker.io/name]
bc3a44f1d009: Preparing
deb5268d1ba0: Preparing
f3c9de8c5c46: Preparing
8de021cacf75: Preparing
ff64ee97d76a: Preparing
480f61641fa1: Preparing
b3eaed7a085d: Preparing
1a058d5342cc: Preparing
480f61641fa1: Waiting
b3eaed7a085d: Waiting
1a058d5342cc: Waiting
ff64ee97d76a: Layer already exists
deb5268d1ba0: Layer already exists
8de021cacf75: Layer already exists
f3c9de8c5c46: Layer already exists
bc3a44f1d009: Layer already exists
480f61641fa1: Layer already exists
1a058d5342cc: Layer already exists
b3eaed7a085d: Layer already exists
latest: digest: sha256:1d6cd5d436337f743c0eb422977a80a53d9437bd953f5781dc253c91664bbe15 size: 1998
The push refers to repository [docker.io/name]
tag does not exist: name:1b9a06b7b43acb77807ed03d09da778701382f64
```

This is the second of the two tags defined above.  If I remove the `uses: docker/setup-buildx-action@v1` bit that I added to the workflow (i.e., don't use buildx), it works again:

```
Successfully built 783a0bca1c7b
Successfully tagged name:latest
Successfully tagged name:b67f3a7f3e0fc8b995f18c0825a8737b5dc66a51
...
```

And then later it is able to push both tags to Docker Hub.

So it seems like `buildx` can't handle multiple tags, although it looks like [it supports it upstream](https://github.com/docker/buildx/issues/396) in a single build invocation.

Is this a version issue?  Am I doing something else wrong?

**Comment by humphd** [comment]
Reading other similar issues, I noticed people discussing using [`docker push --all-tags`](https://github.com/actions/virtual-environments/issues/2691#issuecomment-777911076), but this didn't solve it for me (i.e., the tag doesn't exist).

**Comment by crazy-max** [comment]
@humphd 

> ```yaml
>       # Use buildx, which is faster and can optimize the build steps
>       - name: Set up Docker Buildx
>         uses: docker/setup-buildx-action@v1
>         with:
>           install: true
> ```

This step will setup buildx and create a `docker-container` builder ([default behavior](https://github.com/docker/setup-buildx-action#about)). Therefore your image will not be available in the docker store if you want to push it afterwards.

You can use the [`--load` flag](https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#load) to load your image in the docker store:

```yaml
      # Use buildx, which is faster and can optimize the build steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Docker Build and Tag
        run: docker build --load -t name:latest -t name:$GITHUB_SHA --target deploy .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push Docker image tags to Docker Hub
        run: |
          docker push name:latest
          docker push name:$GITHUB_SHA
```

> using `docker push --all-tags`

This will be push ALL images available on the GitHub Runner which is not what you want because it will also push [images preloaded on GitHub Runners](https://github.com/actions/virtual-environments/blob/340b210bd148ad566675062399cefbad224d713f/images/linux/toolsets/toolset-2004.json#L206-L228).

But you can push all tags for a specific image if you don't specify tags with `docker push name`.

___

As a side note I would suggest to use our [build-push-action](https://github.com/docker/build-push-action). I'm not sure what kind of use case you have but if you want to test your image before pushing it, you can follow this example: https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md
