### ISSUE TITLE
Pass env variables

### ISSUE THREAD

**Issue by bschilder** [docker/setup-buildx-action#123]
I was wondering if it's possible ot pass environmental variables from the GHA workflow yml file into the Dockerfile via the `docker/setup-buildx-action@v1` action.

Something akin to: 

## Yaml 

```yml
...
...
- name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        env:
          pkg: ${{ env.packageName }}
...
...
```

## Dockerfile 

```
RUN mkdir /$pkg
ADD . /$pkg
WORKDIR /$pkg
```

Many thanks, 
Brian

**Comment by crazy-max** [comment]
@bschilder `setup-buildx-action` just sets up the builder and doesn't build anything. However [build-push-action](https://github.com/docker/build-push-action/) does.

Also you want to use [`ARG`](https://docs.docker.com/engine/reference/builder/#arg) to pass variables at build-time to the builder using the [`build-args` input](https://github.com/docker
/build-push-action#inputs):

```dockerfile
ARG PKG
RUN mkdir /$PKG
```


```yaml
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/app:latest
          build-args: |
            PKG=${{ env.packageName }}
```
