### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by dimaqq** [docker/setup-buildx-action#124]
A newbie here, I've tried to set up build in my repo to push to ghcr.io (slug connected to my repo)
I got it work locally using `netkos/act` but it fails on GitHub.

I suspect that automatic github action token is perhaps missing permissions (?) 
(Permissions are set to full in the repo settings / actions / token perms)

#### Actual behaviour

```
#23 exporting to image
#23 pushing layers 0.3s done
#23 ERROR: unexpected status: 403 Forbidden
------
 > importing cache manifest from ghcr.io/dimaqq/dynalite:latest:
------
------
 > exporting to image:
------
error: failed to solve: unexpected status: 403 Forbidden
Error: buildx failed with: error: failed to solve: unexpected status: 403 Forbidden
```

### Configuration

* Repository URL (if public): https://github.com/dimaqq/dynalite-docker
* Build URL (if public): https://github.com/dimaqq/dynalite-docker/runs/4947443696?check_suite_focus=true

```yml
name: ci

on:
  push:
    branches:
      - 'release'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dynalite:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/dynalite:latest
          cache-to: type=inline
```

### Logs

[logs_11.zip](https://github.com/docker/setup-buildx-action/files/7939251/logs_11.zip)

**Comment by crazy-max** [comment]
@dimaqq Does it work if you remove the `permissions:` block?

**Comment by dimaqq** [comment]
Nope, it fails with the same error.

**Comment by mconigliaro** [comment]
Same problem here running locally with act. It seems to work on GitHub though.

**Comment by crazy-max** [comment]
This looks like an issue with registry cache on ghcr.io. Can you try with:

```yaml
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dynalite:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/dynalite:buildcache
          cache-to: type=registry,ref=user/app:buildcache,mode=max
```

If it doesn't work you can switch to the [`gha` cache type](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api):

```yaml
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dynalite:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
