### ISSUE TITLE
Action uselessly requires a running daemon with Kubernetes driver 

### ISSUE THREAD

**Issue by antoinedeschenes** [docker/setup-buildx-action#135]
#### Steps to reproduce this issue

1. Setup a self-hoster runner without any docker daemon.
2. Use docker/setup-buildx-action with `driver: kubernetes`

#### Expected behaviour

`docker buildx create` should create a new builder instance.

#### Actual behaviour

Action fails during the `Docker info` step, as it calls `docker version` and `docker info`, both of which expect a running docker daemon.
https://github.com/docker/setup-buildx-action/blob/20111c644724909db5e5afbf25d7de40ddf74f0b/src/main.ts#L13-L16

### Configuration 

```yml
jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: kubernetes
          driver-opts: |
            namespace=my-namespace
            requests.cpu=1
            limits.cpu=1
            requests.memory=1Gi
            limits.memory=1Gi
            nodeselector=kubernetes.io/arch=amd64
            rootless=true
```

### Logs

Example of Docker info step:
```
$ docker version
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:08:43 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```
