### ISSUE TITLE
Github action with buildx is way slower than normal build

### ISSUE THREAD

**Issue by anuj-scanova** [docker/setup-buildx-action#154]
Used the following workflow to build a docker image for the `arm64` architecture.

```yml
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get Tags for Image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.event.release.tag_name }}
            type=sha

      - name: Docker build/tag/push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
```
and it took approx 22 minutes to build the image
<img width="1069" alt="Screen Shot 2022-06-30 at 9 26 53 PM" src="https://user-images.githubusercontent.com/105233146/176723561-7d452570-6943-4423-8384-6a569d44015c.png">

while running the build without using `buildx` is taking approx **4 minutes** only.
<img width="1066" alt="Screen Shot 2022-06-30 at 9 32 51 PM" src="https://user-images.githubusercontent.com/105233146/176724903-6e5cb06f-ea30-4c61-a05b-86b1b76ca6cf.png">

with the coming workflow. 
```yml
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          IMAGE_NAME: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
        run: |
          docker build -t $IMAGE_NAME .
          echo "::set-output name=image::$IMAGE_NAME"
```
