### ISSUE TITLE
push to GCP randomly failed with error "failed to authorize: failed to fetch oauth token: unexpected status: 404 Not Found"

### ISSUE THREAD

**Issue by alex-blazh** [docker/setup-buildx-action#155]
#### Steps to reproduce this issue

1. use setup-buildx-action and try to push image to google artifact registry 
2.
3.

#### Expected behaviour
image has to be successfully pushed to registry 

#### Actual behaviour
Randomly build failed with error:
`10 ERROR: failed to authorize: failed to fetch oauth token: unexpected status: 404 Not Found`
after several runs it's working again without any code or settings modification.

### Configuration

```yml
build:
    needs: [ setup ]
    runs-on: ubuntu-20.04
    steps:
      ### Clone repo source
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      ### Setup cache layers for Docker
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{hashFiles('ci/.tmp/artifact/name')}}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{hashFiles('ci/.tmp/artifact/name')}}-buildx-
      ### Prepare Docker toolchain
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      ### Prepare gcloud toolchain
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@2eacbe9af2a0b29f4081be4836b6e59da6e59018 # commit on master @12.02.2021
        with:
          project_id: ${{ secrets.ARTEFACTS_PROJECT }}
          service_account_key: ${{ secrets.ARTEFACTS_CREDENTIALS }}
          export_default_credentials: true
          credentials_file_path: /tmp/secrets/gcloud

      ### Authenticate against GCR
      - run: |
          gcloud auth configure-docker
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      ### Build and push the image
      - uses: docker/build-push-action@v3
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE_PATH }}
          target: ${{ env.TARGET }}
          push: ${{ env.PUSH }}
          build-args: |
            LATEST_TAG=${{ env.LATEST_TAG }}
            ${{ env.BUILD_ARGS }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=local,mode=max,dest=/tmp/.buildx-cache-new
          tags: ${{ env.TAGS }}
          labels: |
            org.label-schema.build-date=${{ env.BUILD_TS }}
.....

```

### Logs

```
#10 pushing layers
#10 ...
#11 [auth] ***/ms/hbl-be:pull,push token for europe-west1-docker.pkg.dev
#11 DONE 0.0s
#10 exporting to image
#10 pushing layers 2.8s done
#10 ERROR: failed to authorize: failed to fetch oauth token: unexpected status: 404 Not Found
```
[docker_build.log](https://github.com/docker/setup-buildx-action/files/9111838/docker_build.log)
