### ISSUE TITLE
Post job `cleanup` takes a long time.

### ISSUE THREAD

**Issue by sinwoobang** [docker/setup-buildx-action#158]
#### Steps to reproduce this issue

1. Setup this job generally.
2. Append a remote builder as discussed on (https://github.com/docker/setup-buildx-action/issues/115). Especially, using [this shortcut](https://github.com/marketplace/actions/append-buildx-nodes) on [the comment](https://github.com/docker/setup-buildx-action/issues/115#issuecomment-1016506603).
3. Build multi-arch images remotely using buildx.
4. Start your workflow and see how long it takes to be removed at the last.

#### Expected behaviour

> The builder is removed in a couple of seconds, or at most a minute.

#### Actual behaviour

> It took 15 minutes.

### Configuration

* Repository URL (if public): X
* Build URL (if public): X

```yml
- name: Set up Docker Buildx
  id: builder
  uses: docker/setup-buildx-action@v1

- name: Append ARM buildx builder from AWS
  uses: baschny/append-buildx-action@v1
  with:
    builder: ${{ steps.builder.outputs.name }}
    endpoint: ${{ secrets.SSH_ENDPOINT }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
```

### Logs

I would like to say sorry that I can't attach the log here due to security reasons. Instead, I put a screenshot. It took 16 minutes.
![Screen Shot 2022-09-05 at 12 07 17 AM](https://user-images.githubusercontent.com/6701124/188320837-9ec088a8-cc06-4b10-8947-568752fe0d1b.png)
```
Post job cleanup.
Removing builder
  /usr/bin/docker buildx rm builder-e772f6ea-5196-4636-9999-91548ad9ce9f
  builder-e772f6ea-5196-4636-9999-91548ad9ce9f removed
```
