### ISSUE TITLE
`save-state` and `set-output` deprecation warnings

### ISSUE THREAD

**Issue by hemberger** [docker/setup-buildx-action#168]
### Behaviour

Hi docker devs! This may already be a known issue, but using `docker/setup-buildx-action@v2` results in some span about deprecated commands `save-state` and `set-output`.

#### Steps to reproduce this issue

1. Just include the `docker/setup-buildx-action@v2` action at any step of a workflow.

#### Expected behaviour

No warnings.

#### Actual behaviour

> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Configuration

* Repository URL (if public): https://github.com/smrealms/smr
* Build URL (if public): https://github.com/smrealms/smr/actions/runs/3233150083/jobs/5294632144

```yml
name: CI

on:
  # Run tests for pull requests or pushes to the main branch
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            NO_DEV=0
          tags: local/smr:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

### Logs

[logs_1650.zip](https://github.com/docker/setup-buildx-action/files/9763211/logs_1650.zip)

Thank you for your time!
