### ISSUE TITLE
Consistent `Cannot connect to the Docker daemon` issue on CI

### ISSUE THREAD

**Issue by ra0x3** [docker/setup-buildx-action#176]
### Behaviour

- I'm getting a consistent error when trying to use the `setup-buildx-action`
- The error is consistent in that it happens on each push
  - Sometimes it happens for target `x86_64-unknown-linux-gnu`, then sometimes it happens for target `x86_64-apple-darwin`
    - It has primarily been happening for `x86_64-apple-darwin`

```text
  ERROR: failed to initialize builder builder-a9707d5d-0e81-4fb9-9d1f-4c4408494f56 (builder-a9707d5d-0e81-4fb9-9d1f-4c4408494f560): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Error: The process '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/docker-setup-buildx-OSo80H/bin/buildx' failed with exit code 1
```

#### Steps to reproduce this issue

- Reproducing exact behavior might be hard
- I have included links to the public action on the public repository however

#### Expected behaviour

> Tell us what should happen

- I expect the simple `setup-buildx-action` to not fail. This failure is new behavior

#### Actual behaviour

> Tell us what happens instead

- I get a very consistent failure related to `docker` not running?

### Configuration

* Repository URL (if public): https://github.com/FuelLabs/ci-dummy-test
* Build URL (if public):  https://github.com/FuelLabs/ci-dummy-test/actions/runs/3370479770/jobs/5591626591

```yml
  publish-fuel-indexer-binaries:
    name: Release fuel-indexer binaries
    runs-on: ${{ matrix.job.os }}
    needs:
      - cancel-previous-runs
      # - cargo-test-workspace-all-features
      # - cargo-verifications
    # if: github.event_name == 'release' && github.event.action == 'published'
     # Only do this job if publishing a release
    strategy:
      matrix:
        job:
          # TODO: Add other targets as needed, using fuel-core as reference
          - os: ubuntu-latest
            platform: linux
            target: x86_64-unknown-linux-gnu
            cross_image: x86_64-linux-gnu
          # - os: macos-latest
          #   platform: darwin
          #   target: x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
