### ISSUE TITLE
buildx unable to resolve HTTP based registry

### ISSUE THREAD

**Issue by JohnTGZ** [docker/setup-buildx-action#177]
### Behaviour
During the `docker/build-push-action@v3` step, when an image is being fetched from a local HTTP registry in the `FROM` INSTRUCTION within the dockerfile. The following error occurs:
```
Error: buildx failed with: error: failed to solve: <REGISTRY_ADDRESS>:5000/<ENDPOINT>: failed to do request: Head "https://<REGISTRY_ADDRESS>:5000/<ENDPOINT>": http: server gave HTTP response to HTTPS client
```
#### Background

I'm running a github action workflow on a self-hosted runner and there is a local HTTP registry on the machine. The github action workflow works fine without the `setup-buildx-action` step. However, I'm trying to add this step so that the build can better utilise caching with `docker/build-push-action@v3`. 
This HTTP registry has already been added to the list of insecure registries.

#### Steps to reproduce this issue

1. The github workflow step that has been added:
```
    steps:
      ...
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: network=host
          config: .github/buildkitd.toml
       ...
```
2. The buildkitd.toml file that has been linked to. Where <REGISTRY_ADDRESS> is a placeholder for the local HTTP registry Im linking to 
```
[registry."<REGISTRY_ADDRESS>:5000"]
  http = true
  insecure = true
``` 
3. The `docker/build-push-action@v3` step references a Dockerfile which fetches an image from said registry using the `FROM` instruction.

#### Expected behaviour

The workflow should be able to execute a fetch of the docker image successfully.

#### Actual behaviour

The workflow should is not able to fetch the docker image from the local HTTP registry. Expecting a HTTPS response from a HTTP registry

### Configuration

workflow.yml
```yml
name: CI Docker build & push

on:
  push:
    branches: [ "build/branch_name" ]
  pull_request:
    branches: [ "build/branch_name" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: network=host
          config: .github/buildkitd.toml
      # ###
      # Build base images
      # ###
      -
        name: Build builder
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .../builder.Dockerfile
          build-args: |
            ...
          push: false
          tags: ...
```

buildkitd.toml
```
debug = true
# root is where all buildkit state is stored.
root = "/var/lib/buildkit"
# insecure-entitlements allows insecure entitlements, disabled by default.
insecure-entitlements = [ "network.host", "security.insecure" ]

[grpc]
  address = [ "tcp://0.0.0.0:1234" ]
  # debugAddress is address for attaching go profiles and debuggers.
  debugAddress = "0.0.0.0:6060"
  uid = 0
  gid = 0
  [grpc.tls]
    cert = "/etc/buildkit/tls.crt"
    key = "/etc/buildkit/tls.key"
    ca = "/etc/buildkit/tlsca.crt"

[worker.oci]
  enabled = true
  # platforms is manually configure platforms, detected automatically if unset.
  platforms = [ "linux/amd64", "linux/arm64" ]
  snapshotter = "auto" # overlayfs or native, default value is "auto".
  rootless = false # see docs/rootless.md for the details on rootless mode.
  # Whether run subprocesses in main pid namespace or not, this is useful for
  # running rootless buildkit inside a container.
  noProcessSandbox = false
  gc = true
  gckeepstorage = 9000
  # alternate OCI worker binary name(example 'crun'), by default either 
  # buildkit-runc or runc binary is used
  binary = ""
  # name of the apparmor profile that should be used to constrain build containers.
  # the profile should already be loaded (by a higher level system) before creating a worker.
  apparmor-profile = ""
  # limit the number of parallel build steps that can run at the same time
  max-parallelism = 4
  # maintain a pool of reusable CNI network namespaces to amortize the overhead
  # of allocating and releasing the namespaces
  cniPoolSize = 16

  [worker.oci.labels]
    "foo" = "bar"

  [[worker.oci.gcpolicy]]
    keepBytes = 512000000
    keepDuration = 172800
    filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
  [[worker.oci.gcpolicy]]
    all = true
    keepBytes = 1024000000

[worker.containerd]
  address = "/run/containerd/containerd.sock"
  enabled = true
  platforms = [ "linux/amd64", "linux/arm64" ]
  namespace = "buildkit"
  gc = true
  # gckeepstorage sets storage limit for default gc profile, in MB.
  gckeepstorage = 9000
  # maintain a pool of reusable CNI network namespaces to amortize the overhead
  # of allocating and releasing the namespaces
  cniPoolSize = 16

  [worker.containerd.labels]
    "foo" = "bar"

  [[worker.containerd.gcpolicy]]
    keepBytes = 512000000
    keepDuration = 172800 # in seconds
    filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
  [[worker.containerd.gcpolicy]]
    all = true
    keepBytes = 1024000000

[registry."<REGISTRY_ADDRESS>"]
  http = true
  insecure = true
```
