### ISSUE TITLE
Question about using buildx

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [docker/setup-buildx-action#179]
Hey! Currently I met the issue when I need to pass Environment Variables with custom settings.
How I can pass Environment variable into buildx container?
 
I can't find this possibility on documentation

**Comment by crazy-max** [comment]
You can pass envs using the [`driver-opts` input](https://github.com/docker/setup-buildx-action#inputs):

```yaml
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            env.FOO=bar
            env.MYENV=foo
```

@jedevc I think we miss [that key](https://github.com/docker/buildx/blob/d1b454232d8ea682f3a52a11d28ecc72fd79d7a2/driver/docker-container/factory.go#L54-L59) in ours docs: https://docs.docker.com/build/building/drivers/docker-container/#synopsis
