### ISSUE TITLE
The action is not downloading the correct binary architecture (AMD64 instead of ARM64 on macos)

### ISSUE THREAD

**Issue by SirMishaa** [docker/setup-buildx-action#183]
#### Expected behaviour

It downloads the appropriate build (`buildx-v0.9.1.darwin-arm64,` for example) when running on a runner in ARM64 architecture.  

#### Actual behaviour

> Tell us what happens instead

It's downloading the AMD64 based buildx binary 

![image](https://user-images.githubusercontent.com/42717232/206446343-01eeb84d-bef7-483f-91c4-1208c14adee2.png)

### Configuration

```yml
name: Build and push base image to ECR

on:
  push:
    paths:
      - base.Dockerfile
    branches:
      - master
      - feat/dockerfile-arm64

permissions:
  contents: read

jobs:
  build-push:
    strategy:
      matrix:
        CPU_ARCHITECTURE: [linux/amd64, linux/arm64]
    runs-on: ${{ matrix.CPU_ARCHITECTURE == 'linux/amd64' && 'ubuntu-latest' || 'macos-12' }}
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Check out code
      uses: actions/checkout@v3

      # Docker is not installed by default on macos base image for license reason : https://github.com/actions/runner-images/issues/17
    - name: Setup Docker and Colima
      if: ${{ matrix.CPU_ARCHITECTURE == 'linux/arm64' }}
      run: | 
        brew install docker colima
        colima start

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: ${{ matrix.CPU_ARCHITECTURE }}

    - name: Build, tag and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE: oooooooo
        TAG: latest
      run: |
        HASH=$(git rev-parse --short ${{ github.sha }})
        docker buildx build --platform ${{ matrix.CPU_ARCHITECTURE }} -t $ECR_REGISTRY/$IMAGE:$TAG -t $ECR_REGISTRY/$IMAGE:$HASH . -f ./base.Dockerfile
        docker push $ECR_REGISTRY/$IMAGE:$TAG
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
