### ISSUE TITLE
Cannot find buildx v0.9.1 release

### ISSUE THREAD

**Issue by AlanMendicutti** [docker/setup-buildx-action#190]
### Behaviour
Running this action is returning the next message: "Cannot find buildx v0.9.1 release"

This is the step:
```
name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          version: v0.9.1
```

And this is what RUN returns:
```
 with:
    version: v0.9.1
    driver: docker-container
    buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    install: false
    use: true
```

I've been using this version since a few weeks.
Then all of the sudden this error shows up.

Does anyone knows what's going on?
Thanks in advance

**Comment by farvour** [comment]
We're having this problem with any release tag, including `latest`. It suddenly cropped up in the last 30 minutes or so.

**Comment by crazy-max** [comment]
@AlanMendicutti Please post the logs of the action thanks.

**Comment by farvour** [comment]
> @AlanMendicutti Please post the logs of the action thanks.

```Run docker/setup-buildx-action@v2
  with:
    version: latest
    endpoint: github-selfhosted-context
    driver: docker-container
    buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    install: false
    use: true
  env:
    AWS_DEFAULT_REGION: us-gov-west-1
    AWS_REGION: us-gov-west-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
Docker info
  /usr/local/bin/docker version
  Client:
   Version:           20.10.21
   API version:       1.41
   Go version:        go1.18.7
   Git commit:        baeda1f
   Built:             Tue Oct 25 17:56:30 2022
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  
  Server: Docker Engine - Community
   Engine:
    Version:          20.10.21
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.18.7
    Git commit:       3056208
    Built:            Tue Oct 25 18:02:03 2022
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          v1.6.9
    GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
   runc:
    Version:          1.1.4
    GitCommit:        v1.1.4-0-g5fd4c4d1
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  /usr/local/bin/docker info
  Client:
   Context:    default
   Debug Mode: false
  
  Server:
   Containers: 0
    Running: 0
    Paused: 0
    Stopped: 0
   Images: 1
   Server Version: 20.10.21
   Storage Driver: overlay2
    Backing Filesystem: xfs
    Supports d_type: true
    Native Overlay Diff: true
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: cgroupfs
   Cgroup Version: 1
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
   runc version: v1.1.4-0-g5fd4c4d1
   init version: de40ad0
   Security Options:
    seccomp
     Profile: default
   Kernel Version: 5.4.226-129.415.amzn2.x86_64
   Operating System: Alpine Linux v3.17 (containerized)
   OSType: linux
   Architecture: x86_64
   CPUs: 8
   Total Memory: 30.91GiB
   Name: <redacted>
   ID: O4OL:EM3H:RPFW:KTSM:INYY:OLMB:EN7P:DJF5:FTOP:JKDI:FAKN:VKFM
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Username: <redacted>
   Registry: https://index.docker.io/v1/
   Labels:
   Experimental: false
   Insecure Registries:
    127.0.0.0/8
   Live Restore Enabled: false
   Product License: Community Engine
  
Download and install buildx
  Error: Cannot find buildx latest release```

**Comment by quidquid** [comment]
Same, just started a few minutes ago. Here's the step:
```
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          endpoint: builders
```

And the output:
```
Download and install buildx
  Error: Cannot find buildx latest release
```
