### ISSUE TITLE
GHES: parameter token or opts.auth is required

### ISSUE THREAD

**Issue by zetaab** [docker/setup-buildx-action#194]
#### Steps to reproduce this issue

1. use this action in GHES
2.
3.

#### Expected behaviour

I expect that it should work like before

#### Actual behaviour

![image](https://user-images.githubusercontent.com/22482503/215267087-5f51e602-44c5-49d1-9953-f80fdbfd0585.png)

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
jobs:
  build:
    runs-on:
    - self-hosted
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
