### ISSUE TITLE
Docker not working on macos-latest

### ISSUE THREAD

**Issue by verdverm** [docker/setup-buildx-action#201]
```yaml
...
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
...
```

### Configuration

* Repository URL (if public): https://github.com/hofstadter-io/hof/blob/_dev/.github/workflows/hof.yml#L31
* Build URL (if public): https://github.com/hofstadter-io/hof/actions/runs/4098184664/jobs/7067102591#step:5:27

(note, we currently have it disabled)

### Logs

![image](https://user-images.githubusercontent.com/1390600/216851451-7ce9a4ac-4c27-42f9-b875-8b8f8d73d1b7.png)

### Related

- https://github.com/actions/runner-images/issues/17
- https://github.com/docker-practice/actions-setup-docker/issues/27
