### ISSUE TITLE
Please add a consistent `registry:` parameter to all docker actions

### ISSUE THREAD

**Issue by justinmchase** [docker/setup-buildx-action#224]
### Behaviour

The `docker/login-action` has a `registry:` parameter which can be used to log into a specific registry.

This action attempts to pull an image from the public registry, which is blocked by my corporate firewall. The `actions/setup-qemu-action` has a different `image:` parameter that needs to get set to load from a different registry.

This action requires yet a 3rd way to set the registry:
https://docs.docker.com/build/ci/github-actions/configure-builder/#version-pinning

```yml
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2
  with:
    driver-opts: image=moby/buildkit:v0.11.0
```

Therefore the request here, is to have a consistent way to set the registry across _all_ docker actions.

Intuitively for me that would be the simple to understand `registry: <string>` parameter, which if set would cause all docker images to be pulled from that registry instead of the default public registry.

#### Steps to reproduce this issue

1. Configure your pipeline with this step:
```yml
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2
  with:
    registry: ${{ vars.DOCKER_REGISTRY }}
```

#### Expected behaviour

The `moby/buildkit` image should be pulled from the configured registry.

#### Actual behaviour

The `moby/buildkit` image is pulled from the public docker registry.

### Configuration

```yml
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2
  with:
    driver-opts: image=${{ vars.DOCKER_REGISTRY}}/moby/buildkit:v0.11.0
```

## Related To
https://github.com/docker/setup-qemu-action/issues/76
