### ISSUE TITLE
Error: Certificate has expired

### ISSUE THREAD

**Issue by acullenn** [docker/setup-buildx-action#225]
### Behaviour
This ran fine just a few hours ago, so this must be freshly expired - flagging for the maintainers

The following is observed in GitHub Actions runs that leverage the setup-buildx-action
```
Run docker/setup-buildx-action@v2
Docker info
Download buildx from GitHub Releases
Error: certificate has expired
```

#### Steps to reproduce this issue

1. Run a Github Action that uses the Setup Docker Buildx action
2. Encounter certificate expiration error

#### Expected behaviour
1. Docker buildx is setup

This ran correctly at 14:04 GMT today
```
Fri, 24 Mar 2023 14:04:50 GMT   Run docker/setup-buildx-action@v2
Fri, 24 Mar 2023 14:04:50 GMT   Docker info
Fri, 24 Mar 2023 14:04:50 GMT   Download buildx from GitHub Releases
Fri, 24 Mar 2023 14:04:51 GMT   Downloading https://github.com/docker/buildx/releases/download/v0.10.4/buildx-v0.10.4.linux-amd64
Fri, 24 Mar 2023 14:04:51 GMT   Install buildx
```

#### Actual behaviour

Errors with cert expiration msg

### Configuration

```yml
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          use: true
          version: latest
          endpoint: builders
```

### Logs
https://pastebin.com/XBTgYjvb
```
96 Download buildx from GitHub Releases
97 Error: certificate has expired
```
