### ISSUE TITLE
Using config-inline to declare a Dockerhub mirror has no effect

### ISSUE THREAD

**Issue by gendergap** [docker/setup-buildx-action#232]
### Behaviour

My company is using a Dockerhub mirror (direct access to the Internet in the build context is not possible) which I want to combine with the Buildx setup action like [shown in this documentation](https://docs.docker.com/build/ci/github-actions/configure-builder/#registry-mirror). So far, I had no success with this. The actual build steps always try to contact the real Dockerhub instead of the mirror.

#### Steps to reproduce this issue

1. Configure a GitHub pipeline with the setup action configured to use a mirror
2. Re-use the configured builder in the pipeline step for building images
3. Create some Dockerfile that extends an image from Dockerhub
4. Run the pipeline in GitHub

#### Expected behaviour

I expect that images built by Buildx would honor the mirror configured for Dockerhub and thus pull base images not from _registry-1.docker.io_ but from the mirror site.

#### Actual behaviour

Buildx (according to the output) relentlessly tries to contact Dockerhub directly:

> Error: buildx bake failed with: ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: centos:8.3.2011: failed to do request: Head "https://registry-1.docker.io/v2/library/centos/manifests/8.3.2011": dial tcp 34.194.164.123:443: i/o timeout

### Configuration

```yml
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: setup-builder
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["dockerhub-remote.artifactory.company.int"]
      -
        name: Build and push
        uses: docker/bake-action@v2
        with:
          builder: ${{ steps.setup-builder.outputs.name }}
          workdir: ${{ matrix.image }}
          push: true
```

### Logs

[githubactions-run-log.txt](https://github.com/docker/setup-buildx-action/files/11272637/githubactions-run-log.txt)
[githubactions-cleanup-log.txt](https://github.com/docker/setup-buildx-action/files/11272810/githubactions-cleanup-log.txt)

**Comment by crazy-max** [comment]
Can you post the BuildKit logs please?: https://docs.docker.com/build/ci/github-actions/configure-builder/#buildkit-container-logs

**Comment by gendergap** [comment]
@crazy-max Thanks for the fast response! I appended the cleanup log in my original issue. It is rather unreadable and I hope I managed to sanitize it in an unharmful way.

**Comment by crazy-max** [comment]
It doesn't seem the mirror is working. Looking at one of our e2e job it works on our side: https://github.com/docker/setup-buildx-action/blob/a946f06b5ddbde456d0115dc585e8dc3c7a0c3e0/.github/workflows/ci.yml#L255-L280

Logs: https://github.com/docker/setup-buildx-action/actions/runs/4742043546/jobs/8419873813#step:9:21

```
time="2023-04-19T10:04:44Z" level=debug msg="do request" host=mirror.gcr.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=buildkit/v0.11 request.method=HEAD spanID=46deb3ed064f0d7d traceID=881ad0208fc702140abb57b660299c90 url="https://mirror.gcr.io/v2/library/alpine/manifests/latest?ns=docker.io"
```

Can you try with a simple job in your workflow and let us know?:

```yaml
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Create Dockerfile
        run: |
          cat > ./Dockerfile <<EOL
          FROM centos:8.3.2011
          EOL
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          config-inline: |
            debug = true
            [registry."docker.io"]
              mirrors = ["dockerhub-remote.artifactory.company.int"]
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
```

You should see occurrences of `dockerhub-remote.artifactory.company.int` in the BuildKit logs.
