### ISSUE TITLE
Add parameter when building images

### ISSUE THREAD

**Issue by zambadruzaman** [docker/setup-buildx-action#234]
How if i want to add arguments to the build step? 
I tried the following config, but not working:
 ```
   - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        build-arg: |
          MY_ARG="${{ inputs.my_arg }}"
```
