### ISSUE TITLE
Cannot use previously built images in `FROM` commands

### ISSUE THREAD

**Issue by mythmon** [docker/setup-buildx-action#251]
#### Steps to reproduce this issue

1. Create two dockerfiles, one that uses the first as a `FROM`.
2. Build the first dockerfile in Github Actions, and tag it appropriately
3. Build the second docker file, which starts with `FROM thattag:latest`
4. Use this github action to install buildx, with `install: true`.

I've created a minimal repository that reproduces this issue here: https://github.com/observablehq/buildx-from-reproduction/tree/06f2a9517fab3de8168c4cf1fcbae66b65882ac6. The other commits in that repository represent some other permutations of settings.

#### Expected behaviour

The second dockerfile should be able to access the tagged result of building the first.

#### Actual behaviour

When building the second image, the following error is given on the `FROM` command:

```
 Dockerfile.b:1
--------------------
   1 | >>> FROM a
   2 |     RUN echo "2" > /two
   3 |     
--------------------
ERROR: failed to solve: a: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

You can see the full build here: https://github.com/observablehq/buildx-from-reproduction/actions/runs/5732639937/job/15535956453

### Configuration

* Repository URL (if public): https://github.com/observablehq/buildx-from-reproduction
* Build URL (if public): https://github.com/observablehq/buildx-from-reproduction/actions/runs/5732639937/job/15535956453

```yml
name: Push demo
on:
  push:

jobs:
  Demo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build A
        run: docker build -t a:latest -f Dockerfile.a .
      - name: Build B
        run: docker build -t b:latest -f Dockerfile.b .
```

### Logs

[logs_3.zip](https://github.com/docker/setup-buildx-action/files/12234577/logs_3.zip)

### Other

I've also tried this with `docker buildx build ...`, which can be seen in the latest commit on the reproduction repository.

The commands used in the workflow file work correctly when run locally on my laptop

```
$ docker --version
Docker version 24.0.2, build cb74dfcd85
$ docker buildx version
github.com/docker/buildx 0.11.0 687feca9e8dcd1534ac4c026bc4db5a49de0dd6e
```

**Comment by crazy-max** [comment]
> I've created a minimal repository that reproduces this issue here: https://github.com/observablehq/buildx-from-reproduction/tree/06f2a9517fab3de8168c4cf1fcbae66b65882ac6.

Got a 404 on this repo.

When using `docker/setup-buildx-action@v2` it will create a container builder and therefore the image will not be loaded to the docker store because GitHub Runners are still on Docker 20.10 (it loads by default in docker store only since Docker 23).

You can either use the [`docker` driver](https://docs.docker.com/build/drivers/docker/):

```
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          install: true
```

See https://docs.docker.com/build/ci/github-actions/named-contexts/#use-image-in-subsequent-steps

Or if you want to use the [container driver](https://docs.docker.com/build/drivers/docker-container/), then you need to use a local registry: https://docs.docker.com/build/ci/github-actions/named-contexts/#using-with-a-container-builder
