### ISSUE TITLE
Kubernetes builder is not cleaned when action is cancelled

### ISSUE THREAD

**Issue by gvisca** [docker/setup-buildx-action#279]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

When using the kubernetes driver, the buildx builder instance is not cleaned up when the job is cancelled.

![image](https://github.com/docker/setup-buildx-action/assets/5735781/f91ae541-76f1-434f-bc37-35866c29baed)

### Expected behaviour

The `Post Set up Docker Buildx` step run even if the job is cancelled.

### Actual behaviour

The `Post Set up Docker Buildx` step is also cancelled leaving dangling builders.

### YAML workflow

```yaml
- name: Set up Docker Buildx
        id: setup-builder
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          platforms: linux/amd64
          driver-opts: |
            namespace=actions-runner-system,"nodeselector=kubernetes.io/arch=amd64",requests.cpu=2,requests.memory=2Gi
          append: |
            - platforms: linux/arm64
              driver-opts:
                - namespace=actions-runner-system,"nodeselector=kubernetes.io/arch=arm64",requests.cpu=2,requests.memory=2Gi
```
