### ISSUE TITLE
How to set working directory?

### ISSUE THREAD

**Issue by hinchley2018** [docker/setup-buildx-action#285]
### Description

Not a bug more of a confusion / missing documentation
This action currently assumes the Dockerfile is in the current directory, I have a project that is a monorepo, with a frontend folder that has my docker file in it

I want to pass this docker file to the task, or set current directory??
Read the docs and other issues didn't see anything useful for what i was trying to do
Things I've tried
- Set working directory for the whole job with 
```yaml
defaults:
   run:
      working-directory: ./frontend
```
- the other approach was trying to set the file path with context but vscode was complaining that only inputs are allowed
```yaml
- name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        inputs: 
          file: ./frontend
```

**Comment by crazy-max** [comment]
> This action currently assumes the Dockerfile is in the current directory,

`setup-buildx-action` is only used to manage buildx and builders and doesn't run any build. I think you're looking for https://github.com/docker/build-push-action/.

**Comment by hinchley2018** [comment]
I never said I was trying to run a build, from what I understood in the documentation this task seems to export caches https://github.com/docker/setup-buildx-action#about

This task was auto-generated from microsoft azure when setting up a deploy. 
I already have my build-push-action working 
```yaml
- name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.ACR_REGISTRY }}/frontend:${{ github.sha }}
         context: "{{defaultContext}}:frontend"
```

I'm a bit confused why you closed this issue @crazy-max because my question was not answered...
