### ISSUE TITLE
issues while publishing multi-arch docker images with build kit in GitHub action when using Artiactory as a docker registry

### ISSUE THREAD

**Issue by harishgoudb** [docker/setup-buildx-action#287]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

issues while publishing multi-arch docker images with build kit in GitHub action when using Artiactory as a docker registry

```
#12 [auth] docker-buildx:pull,push token for servername-docker-virtual.jfrog.io
#12 DONE 0.0s

#11 exporting to image
#11 pushing layers 614.6s done
#11 ERROR: failed to push servername-docker-virtual.jfrog.io/docker-buildx:1.2.3: failed commit on ref "layer-sha256:1bbc11c5734e343e8bc59a5fd724b32[91](https://github.com/harishgoudb/Java-Docker/actions/runs/7240950189/job/19724513204#step:9:92)66476d74cc[92](https://github.com/harishgoudb/Java-Docker/actions/runs/7240950189/job/19724513204#step:9:93)5a2f672776b402294a4": failed to do request: Put "https://servername-docker-virtual.jfrog.io/v2/docker-buildx/blobs/uploads/ef435cec-b[93](https://github.com/harishgoudb/Java-Docker/actions/runs/7240950189/job/19724513204#step:9:94)5-422c-9d72-6adff9c0508e?digest=sha256%3A1bbc11c5734e343e8bc59a5fd724b329166476d74cc925a2f672776b4022[94](https://github.com/harishgoudb/Java-Docker/actions/runs/7240950189/job/19724513204#step:9:95)a4": read tcp 172.17.0.3:35622->3.123.220.237:443: read: connection timed out
------
 > exporting to image:
------
ERROR: failed to solve: failed to push servername-docker-virtual.jfrog.io/docker-buildx:1.2.3: failed commit on ref "layer-sha256:1bbc11c5734e343e8bc59a5fd724b329166476d74cc925a2f672776b402294a4": failed to do request: Put "https://servername-docker-virtual.jfrog.io/v2/docker-buildx/blobs/uploads/ef435cec-b935-422c-9d72-6adff9c0508e?digest=sha256%3A1bbc11c5734e343e8bc59a5fd724b329166476d74cc925a2f672776b402294a4": read tcp 172.17.0.3:35622->3.123.220.237:443: read: connection timed out
```

### Expected behaviour

The build should be published as expected with out connectivity errros

### Actual behaviour

The build should be published as expected without connectivity errors

### Workflow run URL

https://github.com/harishgoudb/Java-Docker/actions/runs/7240950189/job/19724513204

### YAML workflow

```yaml
name: Docker-buildx
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: [push, pull_request]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          JF_env:ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
      - name: Setup JFrog CLI
        run: |
          sudo apt-get -y install python3-pip
          sudo pip3 install PyGithub
          sudo pip3 install --upgrade PyGitHub
          sudo pip3 install pyyaml
          sudo pip3 install gql
          sudo apt-get install tcpdump
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3.4.1
        with:
          version: 2.52.3 
        env:
          JF_env_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS }}
      - name: Setup JFrog CLI Config
        run:
          jf c add --url=https://servername.jfrog.io --user 'xxxxxxxxx' --password --interactive=false
      - name: Docker login
        run:
          jf docker login servername-docker-virtual.jfrog.io 
      - name: buildkit
        run: |
          ACTIONS_STEP_DEBUG=
          jf docker context create docker-buildx 
          jf docker buildx create --use docker-buildx
          jf docker buildx build --platform "linux/amd64,linux/arm64" --tag "servername-docker-virtual.jfrog.io/docker-buildx:1.2.3" --push app/
```

### Workflow logs

n/a

### BuildKit logs

```text
n/a
```

### Additional info

n/a
