### ISSUE TITLE
hangs for 2 minutes while storing buildx in cache

### ISSUE THREAD

**Issue by nicks** [docker/setup-buildx-action#293]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

setup-buildx-action consistently hangs for 2 minutes.

### Expected behaviour

No pause

### Actual behaviour

pause

### Repository URL

private

### Workflow run URL

private

### YAML workflow

Relevant snippet:

```yaml

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: my_username
          password: ${{ secrets.MY_PAT }}

      - name: Setup Hydrobuild
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: my-endpoint
          install: true
```

### Workflow logs

```
::group::Inspect builder
Thu, 25 Jan 2024 15:18:40 GMT
Inspect builder
...
Thu, 25 Jan 2024 15:18:40 GMT
  ::endgroup::
Thu, 25 Jan 2024 15:20:48 GMT
##[debug]Node Action run completed with exit code 0
```

(Note the long pause between inspecting the builder and the node action completing)

### Additional info

@crazy-max spent some time poking at this and couldn't figure it out. but some additional data points:

- The pause is consistently reproducible on the first run
- If you re-run the action, the problem goes away
