### ISSUE TITLE
[error]docker: 'buildx' is not a docker command

### ISSUE THREAD

**Issue by socheatsok78** [docker/setup-buildx-action#33]
#### Expected behaviour

> The ci was working just fine last few day. Now i'm having problem with `docker buildx`, `[error]docker: 'buildx' is not a docker command`

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Release Docker Image
on:
  release:
    types: [published]
jobs:
  build:
    name: Build, Tag and Push Image
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    - name: Login to AmazonECR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      name: "Development: Build, Tag and Push Image"
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: |
          NODE_ENV=development
          VUE_APP_VERSION=${{ github.event.release.tag_name }}
          VUE_APP_GIT_SHA=${{ github.sha }}
        tags: |
          ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:dev-latest
          ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.event.release.tag_name }}
```

### Logs
[4_Set up Docker Buildx.txt](https://github.com/docker/setup-buildx-action/files/5479833/4_Set.up.Docker.Buildx.txt)

**Comment by crazy-max** [comment]
@socheatsok78 

> `runs-on: self-hosted`

Looks like you're running on a self-hosted instance. Can you give me the output of the following commands on this instance please?

* `uname -a`
* `docker info`

**Comment by socheatsok78** [comment]
Yes, I'm using `self-hosted`. But it was running fine last few days!

- `uname -a`: Linux gh-runner-1 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- `docker info`:
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 20
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version:
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-52-generic
 Operating System: Ubuntu Core 16
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.807GiB
 Name: gh-runner-1
 ID: WGP2:GKQ3:WSHL:FOCX:QZLD:XW7P:WR6G:F3DF:FV2S:OLA2:LFJV:QMIF
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by crazy-max** [comment]
@socheatsok78 

> But it was running fine last few days!

Nothing has changed since the latest release of this action (5 October) so it should be something with your environment. Can you add this step before `Set up Docker Buildx` step and give me the output please?:

```yaml
    - name: Debug
      run: |
        env|sort
        ls -al ~/.docker/cli-plugins/
```

Can you also [enable runner and step debug](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging) and give me the logs please? Thanks.
