### ISSUE TITLE
"Error: Unexpected token 'j', "json" is not valid JSON"

### ISSUE THREAD

**Issue by matthinrichsen-wf** [docker/setup-buildx-action#346]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Using v3.6.0  in GHA errors with:

"Error: Unexpected token 'j', "json" is not valid JSON"

### Expected behaviour

It should not produce this error

### Actual behaviour

GHA step fails

### YAML workflow

```yaml
jobs:
  build:
    name: Build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: prepare build action
        uses: docker/setup-buildx-action@v3
```

### Additional info

Pinning to v3.5.0 resolves the issue
