### ISSUE TITLE
ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by herberthobregon** [docker/setup-buildx-action#360]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

When I use in ga:
```
jobs:
  build-deploy-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

I get:

ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": unauthorized: incorrect username or password

### Expected behaviour

Works fine

### Actual behaviour

doesn' work

### YAML workflow

```yaml
jobs:
  build-deploy-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

### BuildKit logs

```text
Booting builder
  /usr/bin/docker buildx inspect --bootstrap --builder builder-8dfdcb27-2175-4714-b2cb-312a1c605e4b
  #1 [internal] booting buildkit
  #1 pulling image moby/buildkit:buildx-stable-1
  #1 pulling image moby/buildkit:buildx-stable-1 0.2s done
  #1 ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": unauthorized: incorrect username or password
  ------
   > [internal] booting buildkit:
  ------
  ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": unauthorized: incorrect username or password
Error: ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": unauthorized: incorrect username or password
```

**Comment by rsflaherty** [comment]
https://www.dockerstatus.com/ is showing an issue with personal access tokens against docker hub registry currently.  Not sure if that is related.

**Comment by stdavis** [comment]
This looks like a duplicate of #358 to me.

**Comment by acheung-harmonicinc** [comment]
I run `docker logout` before `docker/setup-buildx-action@v3` then issue is gone.
Not sure if it was a GH issue or setup-buildx-action or dockerhub issue though

**Comment by thaJeztah** [comment]
There was / is an issue with authentication through personal access tokens; see https://www.dockerstatus.com/

**Comment by jacksontj** [comment]
> I run `docker logout` before `docker/setup-buildx-action@v3` then issue is gone. Not sure if it was a GH issue or setup-buildx-action or dockerhub issue though

This workaround also works for me -- presumably just pushing to the un-authed (which isn't impacted by the current issue)

**Comment by herberthobregon** [comment]
I was going crazy. It said but it worked a few hours ago and I didn't change anything 😂

**Comment by devdammit** [comment]
> I run docker logout before docker/setup-buildx-action@v3 then issue is gone.
> Not sure if it was a GH issue or setup-buildx-action or dockerhub issue though
This workaround also works for me! Thanks

**Comment by data-if** [comment]
unexpectedly

**Comment by CumpsD** [comment]
This works:

```yaml
      - name: Fix Docker Hub Issue
        run: docker logout
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
```
