### ISSUE TITLE
Buildkitd-flags causes a weird crash

### ISSUE THREAD

**Issue by fnacarellidev** [docker/setup-buildx-action#364]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Setting `steps.with.buildkitd-flags` to "--allow=network.host" causes a crash.

### Expected behaviour

Expected to run smoothly.

### Actual behaviour

![image](https://github.com/user-attachments/assets/7ac1e778-667e-4b11-b701-808e648760ae)

### Repository URL

https://github.com/fnacarellidev/docker-buildx-action-repro

### Workflow run URL

https://github.com/fnacarellidev/docker-buildx-action-repro/actions/runs/11145581101/job/30975508619

### YAML workflow

```yaml
name: ci
on:
  push:

jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "--allow=network.host"
```

### Workflow logs

[logs_29120860339.zip](https://github.com/user-attachments/files/17230739/logs_29120860339.zip)
