### ISSUE TITLE
Crypto is Not Defined Error

### ISSUE THREAD

**Issue by danielcrabtree** [docker/setup-buildx-action#368]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

v3.7.0 gives `::error::crypto is not defined`, rolling back to v3.6.1 resolves the issue.

### Expected behaviour

v3.7.0 works without any errors.

### Actual behaviour

v3.7.0 gives `::error::crypto is not defined`.

### YAML workflow

```yaml
name: "Deploy Latest"

on:
  push:
    branches: ["develop"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."docker-registry:5000"]
              http = true
              insecure = true
```
