### ISSUE TITLE
DNS Resolution stopped working

### ISSUE THREAD

**Issue by what5150** [docker/setup-buildx-action#379]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

build-push-action@v6 step fails with exit status 128 and a fatal error "Could not resolve host: yyy.xxxx.com". had to add "driver-opts: network=host" to the setup-buildx-action@v3 steps as a workaround. There haven't been any infrastructure changes, no changes to the runner or its host, the workflow hasn't been edited in months. Relates to issue [378](https://github.com/docker/setup-buildx-action/issues/378)

### Expected behaviour

setup-buildx-action@v3 shouldn't need to use host-network. 

### Actual behaviour

Without "driver-opts: network=host" added to the setup-buildx-action@v3 step, DNS breaks.

### YAML workflow

```yaml
name: staging

on:
  pull_request:
    branches: [ 'test' ]

env:
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE_NAME: image_name
  VERSION: 7.4.1.${{ gitea.run_number }}
  ENVIRONMENT: test


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.builder }}
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/organization/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true

      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          repository: organization/argo
          token: ${{ secrets.ARGO_PAT }}
          ref: main

      - name: Update Image Version Var
        run: |
          curl -X 'PUT' \
            'https://gitea.organization.com/api/v1/repos/organization/${{ env.IMAGE_NAME }}/actions/variables/DOCKER_IMAGE_VERSION' \
            -H 'Authorization: token ${{ secrets.ARGO_PAT }}' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{
            "value": "${{ env.VERSION }}"
          }'

      - name: Update Ops Image Version
        working-directory: ${{ env.ENVIRONMENT }}/${{ env.IMAGE_NAME }}
        run: |
          sed -i 's|${{ env.IMAGE_NAME }}:.*|${{ env.IMAGE_NAME }}:'${{ env.VERSION }}'|' config.yaml
          git config --global user.name 'Gitea Actions'
          git config --global user.email 'it@organization.com'
          git add config.yaml
          git commit -m "Update image version to ${{ env.VERSION }}"
          git push
```

### Workflow logs

```
::group::GitHub Actions runtime token ACs
: write
::endgroup::
::group::Docker info
[command]/usr/bin/docker version
Client:
 Version:           26.1.4-1
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b10226d75e8e9a490a31cc3e5b846e0034
 Built:             Wed Jun  5 10:47:13 UTC 2024
 OS/Arch:           linux/amd64
 Context:           default
Server: Docker Engine - Community
 Engine:
  Version:          26.1.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       c8af8eb
  Built:            Mon Apr 22 17:07:12 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[command]/usr/bin/docker info
Client:
 Version:    26.1.4-1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.15.1-1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.28.1-1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
Server:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 28
 Server Version: 26.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-196-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.62GiB
 Name: docker1
 ID: 33155026-bf72-48c7-90da-3e5f0fb15eab
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
WARNING: No swap limit support
::endgroup::
::group::Proxy configuration
No proxy configuration found
::endgroup::
::group::Buildx version
[command]/usr/bin/docker buildx version
github.com/docker/buildx 0.15.1-1 1c1dbb2e4cb5363110f42102744a08d034c2300d
::endgroup::
::group::Builder info
{
  "nodes": [
    {
      "name": "builder-41d492ea-028f-4216-b762-c95467a292760",
      "endpoint": "unix:///var/run/docker.sock",
      "status": "running",
      "buildkitd-flags": "--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host",
      "buildkit": "v0.17.1",
      "platforms": "linux/amd64,linux/amd64/v2,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6",
      "features": {
        "Automatically load images to the Docker Engine image store": true,
        "Cache export": true,
        "Docker exporter": true,
        "Multi-platform build": true,
        "OCI exporter": true
      },
      "labels": {
        "org.mobyproject.buildkit.worker.executor": "oci",
        "org.mobyproject.buildkit.worker.hostname": "230ea3f8392b",
        "org.mobyproject.buildkit.worker.network": "host",
        "org.mobyproject.buildkit.worker.oci.process-mode": "sandbox",
        "org.mobyproject.buildkit.worker.selinux.enabled": "false",
        "org.mobyproject.buildkit.worker.snapshotter": "overlayfs"
      },
      "gcPolicy": [
        {
          "all": false,
          "filter": [
            "type==source.local",
            "type==exec.cachemount",
            "type==source.git.checkout"
          ],
          "keepDuration": "48h0m0s"
        },
        {
          "all": false,
          "keepDuration": "1440h0m0s",
          "keepBytes": "7.451GiB"
        },
        {
          "all": false,
          "keepBytes": "7.451GiB"
        },
        {
          "all": true,
          "keepBytes": "7.451GiB"
        }
      ]
    }
  ],
  "name": "builder-41d492ea-028f-4216-b762-c95467a29276",
  "driver": "docker-container",
  "lastActivity": "2024-11-08T22:58:48.000Z"
}
::endgroup::
[command]/usr/bin/docker buildx build --iidfile /tmp/docker-actions-toolkit-bLan6C/build-iidfile-4ebddf4040.txt --platform linux/amd64 --attest type=provenance,mode=max,builder-id=https://gitea.organization.com/organization/repo/actions/runs/111/attempts/1 --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-actions-toolkit-bLan6C/tmp-490-fblzCYCqh5Mq --tag gitea.organization.com/organization/repo:7.4.1.36 --metadata-file /tmp/docker-actions-toolkit-bLan6C/build-metadata-72cc193c23.json --push https://gitea.organization.com/organization/repo.git#refs/pull/21/head
#0 building with "builder-41d492ea-028f-4216-b762-c95467a29276" instance using docker-container driver
#1 [internal] load git source https://gitea.organization.com/organization/repo.git#refs/pull/21/head
#1 0.159 Initialized empty Git repository in /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/1/fs/
#1 0.212 fatal: unable to access 'https://gitea.organization.com/organization/repo.git/': Could not resolve host: gitea.organization.com
#1 ERROR: failed to fetch remote https://gitea.organization.com/organization/repo.git: git stderr:
fatal: unable to access 'https://gitea.organization.com/organization/repo.git/': Could not resolve host: gitea.organization.com
: exit status 128
------
 > [internal] load git source https://gitea.organization.com/organization/repo.git#refs/pull/21/head:
0.159 Initialized empty Git repository in /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/1/fs/
0.212 fatal: unable to access 'https://gitea.organization.com/organization/repo.git/': Could not resolve host: gitea.organization.com
------
ERROR: failed to solve: failed to read dockerfile: failed to load cache key: failed to fetch remote https://gitea.organization.com/organization/repo.git: git stderr:
fatal: unable to access 'https://gitea.organization.com/organization/repo.git/': Could not resolve host: gitea.organization.com
: exit status 128
::group::Reference
builder-41d492ea-028f-4216-b762-c95467a29276/builder-41d492ea-028f-4216-b762-c95467a292760/psv7svkcz0tp6uqvf4rfxr8nu
```

### BuildKit logs

```text

```
