### ISSUE TITLE
Unable to build docker image via http based registry

### ISSUE THREAD

**Issue by iccfish** [docker/setup-buildx-action#394]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

I've tring to build docker images using builder x via gitea actions.

**The registry**
The registry url was `http://example.com` which resolved to `172.16.1.3`.

**Host config**

Insecure registry configuration in `/etc/docker/daemon.json` was configured:
```
{
	"insecure-registries": [
		"172.16.1.1/8"
	]
}
```

And `docker pull example.com/r/openjdk:8` was works normally as expected.

But builderx failed to build images, although I've add the inscure config in workflow configuration.

### Expected behaviour

I expected builderx build images based on an image served from a http based registry.

### Actual behaviour

In workflow steps, docker login succeed, but builderx failed with following error:
> ERROR: failed to solve: example.com/r/openjdk:8: failed to resolve source metadata for example.com/r/openjdk:8: failed to do request: Head "https://example.com/v2/r/openjdk/manifests/8": remote error: tls: unrecognized name

Trying to add `example.com` as `[registry."example.com"]` in `config-inline` and `buildkitd-config-inline` all without any difference.

### YAML workflow

```yaml
- uses: actions/setup-buildx-action@v3
  with:
    config-inline: |
      [registry."172.16.1.3"] 
        http = true
        insecure = true
    buildkitd-config-inline: |
      [registry."172.16.1.3"] 
        http = true
        insecure = true

- uses: actions/build-push-action@v6
  with:
    file: ./Dockerfile
    push: true
    tags: example.com/***:latest
    platforms: 
      linux/amd64
```

### Workflow logs

```
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 182B done
#1 DONE 0.1s
#2 [internal] load metadata for example.com/r/openjdk:8
#2 ERROR: failed to do request: Head "https://example.com/v2/r/openjdk/manifests/8": remote error: tls: unrecognized name
------
> [internal] load metadata for example.com/r/openjdk:8:
------
Dockerfile:1
--------------------
   1 | >>> FROM example.com/r/openjdk:8
   2 |     EXPOSE 8080
   3 |     
--------------------
ERROR: failed to solve: example.com/r/openjdk:8: failed to resolve source metadata for example.com/r/openjdk:8: failed to do request: Head "https://example.com/v2/r/openjdk/manifests/8": remote error: tls: unrecognized name
Reference
builder-fa311aaf-d48e-4c5e-be62-c82cc175a49a/builder-fa311aaf-d48e-4c5e-be62-c82cc175a49a0/tpts3aa7q7mcml0o4x6byoa76
Check build summary support
::error::buildx failed with: ERROR: failed to solve: example.com/r/openjdk:8: failed to resolve source metadata for example.com/r/openjdk:8: failed to do request: Head "https://example.com/v2/r/openjdk/manifests/8": remote error: tls: unrecognized name
```

### BuildKit logs

```text

```
