### ISSUE TITLE
Random crashes when building Image for 'linux/arm64'

### ISSUE THREAD

**Issue by gerb-ster** [docker/setup-buildx-action#403]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Since a couple of days my Github Action I've setup to build & push a container image keeps failing. Sometimes it works & completes, but most of the time it fails when these kind of messages:

```
ERROR: failed to solve: process "/bin/sh -c docker-php-ext-install pdo_mysql" did not complete successfully: exit code: 77
```
or

```
checking whether the C compiler works... configure: error: in `/usr/src/php/ext/zip':
configure: error: cannot run C compiled programs.
```
or

```
ERROR: failed to solve: process "/bin/sh -c docker-php-ext-install zip" did not complete successfully: exit code: 77
```

I haven't changed or modified my GitHubAction yml file recently; it's very strange because sometimes (1 or 2 times out of 10) it runs and completes succesfully.

The content of my github action file:

```
name: Build & Push

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: ${{ github.repository }}
  TAG_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Composer update & install
        run: cd web-app/ && composer update && composer install --prefer-dist --no-suggest --no-progress

      - name: NPM install & build
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: cd web-app/ && npm install
      - run: cd web-app/ && npm run build
      - run: cd web-app/ && npm prune --production
      - run: rm -Rf web-app/node_modules/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./web-app
          file: ./web-app/docker/backend.prod.dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### Expected behaviour

I would expect consistent results, either failed or succeeded builds. 

### Actual behaviour

Builds seem te fail at random, with different results

### YAML workflow

```yaml
name: Build & Push

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: ${{ github.repository }}
  TAG_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Composer update & install
        run: cd web-app/ && composer update && composer install --prefer-dist --no-suggest --no-progress

      - name: NPM install & build
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: cd web-app/ && npm install
      - run: cd web-app/ && npm run build
      - run: cd web-app/ && npm prune --production
      - run: rm -Rf web-app/node_modules/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./web-app
          file: ./web-app/docker/backend.prod.dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### BuildKit logs

```text

```
