### ISSUE TITLE
Build logs should go in temporary directory

### ISSUE THREAD

**Issue by wyardley** [docker/setup-buildx-action#409]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

Is it possible to configure the defaults to put debug logging etc. in a different directory from the GitHub workspace?

I end up with a `buildkitd.toml` and `buildkitd.log` if I do a Docker build with these files not `.dockerignored` and do a top level `COPY ./ ./`. While this is easy to not do,

### Expected behaviour

No buildkit config / log files in a built image.

### Actual behaviour

`buildkitd.log` and `buildkitd.toml` are present.

### YAML workflow

```yaml
steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker tags and metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 9
        with:
          images: ${{ env.IMAGE }}
          labels: |
            org.opencontainers.image.description=Blah blah
            org.opencontainers.image.licenses=UNLICENSED
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
      # [...]
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push image
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### BuildKit logs

```text

```
