### ISSUE TITLE
Cannot connect to docker daemon - docker 28.1.0

### ISSUE THREAD

**Issue by andrew-magic** [docker/setup-buildx-action#418]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Looks like docker pushed a new 28.1.0 2 hours ago with new features around socket usage: https://docs.docker.com/engine/release-notes/28/ 

This new version of the docker installation is not allowing socket connection:
```
Docker info
  /home/ubuntu/bin/docker version
  Client:
   Version:           28.1.0
   API version:       1.49
   Go version:        go1.23.8
   Git commit:        4d8c241
   Built:             Thu Apr 17 09:53:56 2025
   OS/Arch:           linux/amd64
   Context:           default
  Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
  The process '/home/ubuntu/bin/docker' failed with exit code 1
```

### Expected behaviour

Connect to the socket and use docker.

### Actual behaviour

This new version of the docker installation is not allowing socket connection:
```
Docker info
  /home/ubuntu/bin/docker version
  Client:
   Version:           28.1.0
   API version:       1.49
   Go version:        go1.23.8
   Git commit:        4d8c241
   Built:             Thu Apr 17 09:53:56 2025
   OS/Arch:           linux/amd64
   Context:           default
  Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
  The process '/home/ubuntu/bin/docker' failed with exit code 1
```

### YAML workflow

```yaml
name: Publish Workflow

on:
  workflow_call:
    inputs:
      aws_account:
        description: 'The aws_account to run tests with'
        type: string
        required: true
      aws_region:
        description: 'The aws_region to run tests with'
        type: string
        required: true
      aws_role_name:
        description: 'The aws_role_name to run tests with'
        type: string
        required: true
      node:
        description: 'The Node version to run tests with'
        type: string
        required: true
      python:
        description: 'The Python version to run tests with'
        type: string
        required: true
    outputs:
      image_tag:
        description: The image tag
        value: ${{ jobs.base.outputs.image_tag }}

permissions:
  pull-requests: write # so we can comment on PR
  id-token: write # This is required for aws creds requesting the JWT
  contents: read  # This is required for aws creds actions/checkout

jobs:
  base:
    outputs:
      image_tag: ${{ steps.git-commit.outputs.image_tag }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account }}:role/${{ inputs.aws_role_name }}
        aws-region: ${{ inputs.aws_region }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Get short git hash
      id: git-commit
      run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

    - name: Build Image
      env:
        REGISTRY: "${{ inputs.aws_account }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com"
        REPOSITORY: "xxx"
        IMAGE_TAG: "${{ steps.git-commit.outputs.short_sha }}"
      working-directory: .
      run: |
        docker build --target runtime -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

    - name: Tag and Push to ECR
      env:
        REGISTRY: "${{ inputs.aws_account }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com"
        REPOSITORY: "xxx"
        IMAGE_TAG: "${{ steps.git-commit.outputs.short_sha }}"
      working-directory: .
      run: |
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
        docker push $REGISTRY/$REPOSITORY:latest
```

### BuildKit logs

```text

```

**Comment by crazy-max** [comment]
What is the output of:

```yaml
jobs:
  base:
    runs-on: self-hosted
    steps:
      run: docker info
```
