### ISSUE TITLE
Crypto Error when using v3 tag

### ISSUE THREAD

**Issue by rogue73** [docker/setup-buildx-action#419]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Hi, 
since a few days I've receive an error if I use the v3 tag:
`::error::crypto is not found`

This is my step in actions:

```
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v3
  with:
    driver: kubernetes
    driver-opts: |
      namespace=git-runner
      qemu.install=true
```

If I use `docker/setup-buildx-action@v3.10.0` everything works as expected. Even if v3 and v3.10.0 points to the same commit.

This error is actual known for version 3.6.0 and was solved with version 3.6.1. 

For me it occurs only with `v3` and `v3.6.0`.

Does anyone else notice this behavior?

Cheers,
Stefan

### Expected behaviour

Using tag v3 without error

### Actual behaviour

tag v3 isn't working and i have to use a explicit version tag like 3.10.0 

### YAML workflow

```yaml
- name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            namespace=git-runner
            qemu.install=true
```

### BuildKit logs

```text

```

**Comment by crazy-max** [comment]
> since a few days I've receive an error if I use the v3 tag:
> `::error::crypto is not found`

Can you show the full yaml workflow and all logs of the `docker/setup-buildx-action` please?

**Comment by rogue73** [comment]
> 
> Can you show the full yaml workflow and all logs of the `docker/setup-buildx-action` step please?

This is the full yaml workflow:

```
name: Build Docker Container Image
on:
  push:

jobs:
  Dev-Build-Docker:
    runs-on: git-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: create kubeconfig
        run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}"  > $HOME/.kube/config
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver: kubernetes
          driver-opts: |
            namespace=git-runner
            qemu.install=true
            cleanup=false
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERID_USER }}
          password: ${{ secrets.DOCKERID_TOKEN }}
      - name: Login to private Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.example.org
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: git.example.org/docker-images/myimagename:latest

``` 
In the  `docker/setup-buildx-action` step i see only this line `::error::crypto is not found`.
I've tried to get more logs with `buildkitd-flags: --debug` and also add `cleanup=false` to keep the builder to debug but I see still only this line.
