### ISSUE TITLE
The action "docker/setup-buildx-action@v3" today it started to give an error "Error: EACCES: permission denied, copyfile"

### ISSUE THREAD

**Issue by bmsilva** [docker/setup-buildx-action#423]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

`setup-buildx-action` started to crash today and can't find the reason why.

### Expected behaviour

It's been running without issues for months, couldn't find what's the root cause.

### Actual behaviour

When starting the workflow it crashes on the `setup-buildx-action` step.

### YAML workflow

```yaml
name: Setup for tests
description: Setup for tests
branding:
  icon: arrow-right-circle
  color: gray-dark
runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "21"
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5
        cache-read-only: false
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: 'tests/requirements.txt'
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
    - name: Expose Github Runtime
      uses: crazy-max/ghaction-github-runtime@v3
```

### Workflow logs

Run docker/setup-buildx-action@v3
Docker info
  /vendor/docker/docker version
  Client:
   Version:           26.1.3
   API version:       1.45
   Go version:        go1.21.10
   Git commit:        b72abbb
   Built:             Thu May 16 08:32:30 2024
   OS/Arch:           linux/amd64
   Context:           default
  Server: Docker Engine - Community
   Engine:
    Version:          26.1.3
    API version:      1.45 (minimum version 1.24)
    Go version:       go1.21.10
    Git commit:       8e96db1
    Built:            Thu May 16 08:33:58 2024
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          v2.0.1
    GitCommit:        88aa2f531d6c2922003cc7929e51daf1c14caa0a
   runc:
    Version:          1.1.12
    GitCommit:        v1.1.12-0-g51d5e94
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  /vendor/docker/docker info
  Client:
   Version:    26.1.3
   Context:    default
   Debug Mode: false
   Plugins:
    buildx: Docker Buildx (Docker Inc.)
      Version:  v0.15.0
      Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
    compose: Docker Compose (Docker Inc.)
      Version:  v2.27.3
      Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  Server:
   Containers: 0
    Running: 0
    Paused: 0
    Stopped: 0
   Images: 0
   Server Version: 26.1.3
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Using metacopy: false
    Native Overlay Diff: true
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: cgroupfs
   Cgroup Version: 2
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: 88aa2f531d6c2922003cc7929e51daf1c14caa0a
   runc version: v1.1.12-0-g51d5e94
   init version: de40ad0
   Security Options:
    seccomp
     Profile: builtin
    cgroupns
   Kernel Version: 6.7.12
   Operating System: Wolfi
   OSType: linux
   Architecture: x86_64
   CPUs: 4
   Total Memory: 15.62GiB
   Name: ul371nkvl0sma
   ID: d38bd99b-6802-4c13-9a62-88880281adbe
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Experimental: false
   Insecure Registries:
    169.254.169.43:6001
    127.0.0.0/8
   Registry Mirrors:
    http://169.254.169.43:6001/
   Live Restore Enabled: false
   Product License: Community Engine
  WARNING: No swap limit support
Download buildx from GitHub Releases
  Use 0.23.0 version spec cache key for v0.23.0
  Cache hit for: buildx-dl-bin-0.23.0-linux-x64
  Received 0 of 19585080 (0.0%), 0.0 MBs/sec
  Received 19585080 of 19585080 (100.0%), 10.5 MBs/sec
  Cache Size: ~19 MB (19585080 B)
  /usr/bin/tar -xf /home/runner/work/_temp/ddd4de0e-2897-4c2d-94d6-5b250933259f/cache.tzst -P -C /home/runner/work/abs/abs --use-compress-program unzstd
  Cache restored successfully
  Restored buildx-dl-bin-0.23.0-linux-x64 from GitHub Actions cache
  Cached to hosted tool cache /opt/hostedtoolcache/buildx-dl-bin/0.23.0/linux-x64
  Buildx binary found in /home/runner/.docker/buildx/.bin/0.23.0/linux-x64/docker-buildx
Install buildx
  Docker plugin mode
Error: EACCES: permission denied, copyfile '/home/runner/.docker/buildx/.bin/0.23.0/linux-x64/docker-buildx' -> '/home/runner/.docker/cli-plugins/docker-buildx'

### BuildKit logs

```text

```
