### ISSUE TITLE
Failed to restore: getCacheEntry failed: connect ETIMEDOUT during the setup and post job cleanup

### ISSUE THREAD

**Issue by richierichard** [docker/setup-buildx-action#426]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Recently we started facing issue where the docker/setup-buildx-action@v3 while downloading the installer tries to get it from cache which timed out after 4 minutes.

Also the post job cleanup is having similar issues due to which we see increase in the overall job completion time. Usually the jobs used to take 3 minutes to complete but now are taking more than 12 minutes.

Attached the screenshots for reference. I think the Github deprecated the version of cache being used in this action, for reference https://github.com/orgs/community/discussions/160793

![Image](https://github.com/user-attachments/assets/6db8f4ed-fde6-49e9-b67b-3b31be6f39ac)
![Image](https://github.com/user-attachments/assets/d83535f9-3ea8-4d7c-b053-15caa9802d03)

### Expected behaviour

There should be no cache error and the time for the action to setup the installer should be in seconds.

![Image](https://github.com/user-attachments/assets/cc41e767-a0bf-48d2-8a95-365707f3327d)
![Image](https://github.com/user-attachments/assets/75131dba-32f1-4993-95da-dd4415bf4d8f)

### Actual behaviour

Currently, it takes more than 5 minutes to setup time installer using the action and the post job cleanup takes another 5 minutes which in total increasing the overall workflow time by 10 minutes.

### YAML workflow

```yaml
build-and-push:
    runs-on: k8s-runner-2xl-arm
    permissions:
      contents: read
      packages: write
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout the code from Github
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
```

### BuildKit logs

```text

```
