### ISSUE TITLE
The builder is always cleaned up with --keep-state argument, regardless of the option set in the action

### ISSUE THREAD

**Issue by xbb** [docker/setup-buildx-action#428]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Hello, 

since the latest version 3.11.0, in the post action, the builder is removed with `--keep-state` by default and even when `keep-state` is set to `false`.

![Image](https://github.com/user-attachments/assets/f9697428-8d92-49c1-8575-872b3bb67491)

![Image](https://github.com/user-attachments/assets/178a0b84-36e7-48c4-9ee7-06c3f8536780)

### Expected behaviour

when the input option `keep-state` is `false`, `buildx rm <builder>` is called without `--keep-state`, 

### Actual behaviour

`buildx rm <builder>` is called with `--keep-state` even when `keep-state` is `false`

### YAML workflow

```yaml
name: Setup Docker Buildx
on:
    workflow_dispatch:
jobs:
  setup-buildx:
    runs-on: [ubuntu-latest]
    steps:
      - name: Defaults
        uses: docker/setup-buildx-action@v3

      - name: Keep state false
        uses: docker/setup-buildx-action@v3
        with:
          keep-state: false

      - name: Name and keep state false
        uses: docker/setup-buildx-action@v3
        with:
          name: test
          keep-state: false
```

### BuildKit logs

```text

```
