### ISSUE TITLE
buildx build fails with error `error: no valid drivers found:` for buildx version `0.5.0`

### ISSUE THREAD

**Issue by akhilerm** [docker/setup-buildx-action#45]
### Behaviour
When the github action is used as follows: 
```
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
```
i.e with the latest version of buildx (0.5.0), the builds are failing with error. [Ref](https://github.com/akhilerm/node-disk-manager/runs/1555045310?check_suite_focus=true)
```
error: no valid drivers found: invalid driver option platform for docker-container driver
make: *** [docker.buildx] Error 1
```

This is the command that we executing and giving the above error
```
	export DOCKER_CLI_EXPERIMENTAL=enabled
	@if ! docker buildx ls | grep -q container-builder; then\
		docker buildx create --platform ${PLATFORMS} --name container-builder --use;\
	fi
	@docker buildx build --platform ${PLATFORMS} \
		-t "$(DOCKERX_IMAGE_NAME)" ${DBUILD_ARGS} -f $(PWD)/build/$(COMPONENT)/Dockerfile \
		. ${PUSH_ARG}
```

#### Steps to reproduce this issue

1. Use `setup-build-action` github action with latest buildx version (0.5.0)
2. Execute the following commands
```
if ! docker buildx ls | grep -q container-builder; then\
		docker buildx create --platform ${PLATFORMS} --name container-builder --use;\
fi
docker buildx build --platform ${PLATFORMS} \
		-t "$(DOCKERX_IMAGE_NAME)" ${DBUILD_ARGS} -f $(PWD)/build/$(COMPONENT)/Dockerfile \
		. ${PUSH_ARG}
```

#### Expected behaviour

> Tell us what should happen

The build process should continue without an error

#### Actual behaviour

> Tell us what happens instead
errors out with 
```
error: no valid drivers found: invalid driver option platform for docker-container driver
```

### Configuration

* Repository URL (if public):  https://github.com/akhilerm/node-disk-manager/tree/ci-test-action
* Build URL (if public): https://github.com/akhilerm/node-disk-manager/runs/1555045310?check_suite_focus=true

```yml
name: ci

on: ['push']

jobs:
  ndm-daemonset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build Image
        env:
          IMG_RESULT: cache
        run: make docker.buildx.ndm
```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
[logs_428.zip](https://github.com/docker/setup-buildx-action/files/5693635/logs_428.zip)
