### ISSUE TITLE
Creating a buildx fails when using matrix strategy on self hosted runners

### ISSUE THREAD

**Issue by malkam03** [docker/setup-buildx-action#47]
### Behavior

When creating a builder instance using GitHub's matrix strategy to build multiple images in parallel the `Creating a new builder instance` action step fails with an error that looks related to the naming strategy used to create new builders:

```bash
📣 Buildx version: 0.4.2
🔨 Creating a new builder instance
  /usr/bin/docker buildx create --name builder-build-linux-images-2 --driver docker-container --driver-opt env.http_proxy=***** --driver-opt env.https_proxy=***** --driver-opt image=******* --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host --use
  existing instance for builder-build-linux-images-2 but no append mode, specify --node to make changes for existing instances
  Error: The process '/usr/bin/docker' failed with exit code 1
```

Probably related to [this line](https://github.com/docker/setup-buildx-action/blob/master/src/main.ts#L30)?

#### Steps to reproduce this issue

1. Set a workflow with whichever trigger you want
2. Add a `setup-buildx-action` to the workflow
3. Parallelize your job with the matrix strategy
4. Run on multiple self-hosted runners on the same server

#### Expected behavior

> The action should assign unique names for the builders

#### Actual behavior

> If the builder is being instantiated with the matrix strategy some of the builders will have the same name

### Configuration

* Repository URL (if public):  Private repo
* Build URL (if public): Private repo

```yml
name: Main-CI

on:
  push:
    branches: [main]
jobs:
  build-linux-images:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        include:
          - package: package1
            directory: docker/linux/package1
          - package: package2
            directory: docker/linux/package2
          - package: package3
            directory: docker/linux/package3
          - package: package4
            directory: docker/linux/package4
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
```
