### ISSUE TITLE
Running in 'act' results in "Unable to locate executable file: docker"

### ISSUE THREAD

**Issue by antonlisovenko** [docker/setup-buildx-action#53]
### Behaviour
When running the github action locally using [act](https://github.com/nektos/act) the build produces:
```
[Deploy Operator to k8s cluster/Deploy to k8s] ⭐  Run Set up Docker Buildx
[Deploy Operator to k8s cluster/Deploy to k8s]   ☁  git clone 'https://github.com/docker/setup-buildx-action' # ref=v1
[Deploy Operator to k8s cluster/Deploy to k8s]   🐳  docker cp src=/Users/alisovenko/.cache/act/docker-setup-buildx-action@v1 dst=/actions/
[Deploy Operator to k8s cluster/Deploy to k8s]   ❓  ::save-state name=isPost::true
[Deploy Operator to k8s cluster/Deploy to k8s]   ❗  ::error::Unable to locate executable file: docker. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[Deploy Operator to k8s cluster/Deploy to k8s]   ❌  Failure - Set up Docker Buildx
```
#### Steps to reproduce this issue

1. install `act`
2. run the following workflow:
```
name: build

jobs:
  build:
    name: Deploy to k8s
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2.3.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
```
`act -j build`

#### Expected behaviour

This is weird as considering that `docker` is packed into the github action (https://github.com/docker/setup-buildx-action/blob/master/Dockerfile#L23) I'd expect that it doesn't need to depend on the Github Action runner and presence of docker there. But it seems that the setup-buildx-action requires the hosting environment to contain docker already.
