### ISSUE TITLE
Setup buildx behind proxy

### ISSUE THREAD

**Issue by kouberl** [docker/setup-buildx-action#57]
### Behaviour

We tried to setup-buildx-action behind proxy. We have a corporate proxy which we address with a cntlm proxy (with saved credentials) listening at http://ip:port (without username and password).
We are running GitHub Enterprise Server 2.22.6 

#### Steps to reproduce this issue

1. setup proxy
2. add setup-buildx-action to gh action
3. trigger action

#### Expected behaviour

> buildx should be set up

#### Actual behaviour

> buildx cannot be set up

### Configuration

```yml

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  docker-build-with-action:
    runs-on: [self-hosted]
    steps:
      - name: See Environment
        run: |
          echo "http_proxy=${http_proxy}"
          echo "https_proxy=${https_proxy}"
          printenv
          npm config get
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/app:latest
      - name: Test
        run: echo "foobar"
```

### Environment 
we have set http_proxy, HTTP_PROXY, https_proxy, HTTPS_PROXY
also in npm
npm config set proxy http://ip:port
npm config set https-proxy http://ip:port
npm config set strict-ssl false
npm config set unsafe-perm true
npm config set registry http://registry.npmjs.org/

### Logs
```
Run docker/setup-buildx-action@v1
  with:
    driver: docker-container
    buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    install: false
    use: true
(node:21338) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:21338) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
👉 Installing Buildx
  ⬇️ Downloading https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64...
  tunneling socket could not be established, statusCode=407
  Waiting 14 seconds before trying again
  tunneling socket could not be established, statusCode=407
  Waiting 19 seconds before trying again
  ##[error]tunneling socket could not be established, statusCode=407
```

**Comment by pzamoran** [comment]
Good Morning. I have a similar problem. I´ve tried using driver-opts (https://github.com/docker/buildx/issues/136):
        with:
          driver-opts: |
            env.http_proxy=${{ env.HTTP_PROXY}}
            env.https_proxy=${{ env.HTTPS_PROXY}}

however, when I´m running the build-push, the proxy config is not present or it is not used.

**Comment by crazy-max** [comment]
@kouberl Sorry for the delay, looks like buildx is not available on your self hosted runner. Can you give me the output of the following steps please?:

```yaml
     - name: Docker info
       run: docker info
     - name: Docker version
       run: docker version
```

@pzamoran 

What version of docker/buildx?:

```yaml
     - name: Docker info
       run: docker info
     - name: Docker version
       run: docker version
```
