### ISSUE TITLE
Specify custom config for buildx

### ISSUE THREAD

**Issue by GMartinez-Sisti** [docker/setup-buildx-action#66]
Hi, I've been trying to use a custom config with the following syntax:

```yaml
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          buildkitd-flags: --config /etc/buildkit/buildkitd.toml
```
```sh
$ cat /etc/buildkit/buildkitd.toml
[registry."docker.io"]
    mirrors = ["nexus.internal.domain"]
```

The docker config also uses the same registry and I can see that the buildx image is pulled from the configured mirror, but images used by buildx are not respecting the configuration and going straight to Docker Hub. Initially I tried to use the variable `DOCKER_CONFIG` but looks like it's only used to specify the plugin directory [here](https://github.com/docker/setup-buildx-action/blob/2a4b53665e15ce7d7049afb11ff1f70ff1610609/dist/index.js#L2199).

Using the configuration locally works with:
```
docker buildx create --config /etc/buildkit/buildkitd.toml --use
```

I'd like to avoid specifying the configuration as arguments to prevent having to change all the workflows every time something changes. Is this feature supported by this action?

(Initial report -> https://github.com/docker/buildx/issues/136)

Thanks
