### ISSUE TITLE
Fails with "Unable to resolve action"

### ISSUE THREAD

**Issue by grahame** [docker/setup-buildx-action#83]
#### Steps to reproduce this issue

1. make a minimal github actions workflow based on README.md: https://github.com/exegeteapp/exegete/blob/6b85e0796852381df96edd8f49747371449e214d/.github/workflows/main.yml
2. run a build: https://github.com/exegeteapp/exegete/runs/2703252517?check_suite_focus=true

#### Expected behaviour

> Buildx and qemu should be installed

#### Actual behaviour

> Fails with error: "Error: Unable to resolve action `moby/moby@v1`, unable to find version `v1`"

### Configuration

* Repository URL (if public): https://github.com/exegeteapp/exegete
* Build URL (if public): https://github.com/exegeteapp/exegete/runs/2703252517?check_suite_focus=true

```yml
name: Continuous Integration and Delivery

on: [push]

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Add .local/bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
```

### Logs

[logs_24.zip](https://github.com/docker/setup-buildx-action/files/6565747/logs_24.zip)
