### ISSUE TITLE
error setup-buildx-action does not find docker

### ISSUE THREAD

**Issue by Al-Murphy** [docker/setup-buildx-action#84]
### Behaviour
I am trying to push a docker image to to dockerhub using github actions with setup-buildx-action but I get a very strange error:

![image](https://user-images.githubusercontent.com/62257358/121082288-c90d8500-c7d5-11eb-8ce6-a16cc6828e07.png)

The issue corresponds to this part of the .yaml file:
```
      - name: Set up Docker Buildx        
      - uses: docker/setup-buildx-action@v1
```

#### Steps to reproduce this issue

1. Use my .yaml file provided below
2. Run with any github repo, mine was an R package which ran a CRAN check beforehand
3. I've also included the Dockerfile I was using

#### Expected behaviour

I expect the Set Up Docker Buildx to find the Dockerfile

#### Actual behaviour

It doesn't seem to

### Configuration

* Private Repo but Dockerfile and .yaml file provided

```yml
AT END WITH DOCKERFILE
```

### Logs

> Attached zipped logfile for github action run
[logs_10.zip](https://github.com/docker/setup-buildx-action/files/6611830/logs_10.zip)

### .yaml file
```
name: R GitHub Actions

on:
  push:
    branches:
      - main
      - master
      - dev-am
  pull_request:
    branches:
      - main
      - master

jobs:
  R-CMD-check:
    name: R-CMD-check
    runs-on: ubuntu-latest
    container: almurphy/scfdev:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RGL_USE_NULL: TRUE
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          install-r: false

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        
      - name: Get R package version
        run: |
          version=$(grep Version DESCRIPTION | grep -o "[0-9.]\+")
          echo "packageVersion=${version}" >> $GITHUB_ENV
        shell: bash {0}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository}}:${{ env.packageVersion }}
```

### Dockerfile
```
#LABEL maintainer="Combiz Khozoie, Ph.D. c.khozoie@imperial.ac.uk, Alan Murphy, a.murphy@imperial.ac.uk"

## Use rstudio installs binaries from RStudio's RSPM service by default, 
## Uses the latest stable ubuntu, R and Bioconductor versions. Created on unbuntu 20.04, R 4.0 and BiocManager 3.12
FROM rocker/rstudio


## Add packages dependencies
RUN apt-get update \
	&& apt-get install -y --no-install-recommends apt-utils \
	&& apt-get install -y --no-install-recommends \
	## Basic deps
	gdb \
	libxml2-dev \
	python3-pip \
	libz-dev \
	liblzma-dev \
	libbz2-dev \
	libpng-dev \
	libgit2-dev \
	## sys deps from bioc_full
	pkg-config \
	fortran77-compiler \
	byacc \
	automake \
	curl \
	## This section installs libraries
	libpcre2-dev \
	libnetcdf-dev \
	libhdf5-serial-dev \
	libfftw3-dev \
	libopenbabel-dev \
	libopenmpi-dev \
	libxt-dev \
	libudunits2-dev \
	libgeos-dev \
	libproj-dev \
	libcairo2-dev \
	libtiff5-dev \
	libreadline-dev \
	libgsl0-dev \
	libgslcblas0 \
	libgtk2.0-dev \
	libgl1-mesa-dev \
	libglu1-mesa-dev \
	libgmp3-dev \
	libhdf5-dev \
	libncurses-dev \
	libbz2-dev \
	libxpm-dev \
	liblapack-dev \
	libv8-dev \
	libgtkmm-2.4-dev \
	libmpfr-dev \
	libmodule-build-perl \
	libapparmor-dev \
	libprotoc-dev \
	librdf0-dev \
	libmagick++-dev \
	libsasl2-dev \
	libpoppler-cpp-dev \
	libprotobuf-dev \
	libpq-dev \
	libperl-dev \
	## software - perl extentions and modules
	libarchive-extract-perl \
	libfile-copy-recursive-perl \
	libcgi-pm-perl \
	libdbi-perl \
	libdbd-mysql-perl \
	libxml-simple-perl \
	libmysqlclient-dev \
	default-libmysqlclient-dev \
	libgdal-dev \
	## new libs
	libglpk-dev \
	## Databases and other software
	sqlite \
	openmpi-bin \
	mpi-default-bin \
	openmpi-common \
	openmpi-doc \
	tcl8.6-dev \
	tk-dev \
	default-jdk \
	imagemagick \
	tabix \
	ggobi \
	graphviz \
	protobuf-compiler \
	jags \
	## Additional resources
	xfonts-100dpi \
	xfonts-75dpi \
	biber \
	libsbml5-dev \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

RUN install2.r -e \
testthat \
covr \
knitr \
purrr \
stringr \
cli \
dplyr \
data.table \
R.utils \
vroom \
ggpubr \
ggplot2 \
rmarkdown \
rlang \
future \
future.apply \
plotly \
threejs \
plyr \
assertthat \
httr \
prettydoc \
leaflet \
gdtools \
formattable \
ggdendro \
ggridges \
cowplot \
forcats \
ggrepel \
igraph \
tibble \
tidyr \
tidyselect \
tidyverse \
ids \
snow \
remotes \
rliger \
argparse \
Hmisc

## Install remaining packages from source
COPY ./misc/requirements-src.R .
RUN Rscript requirements-src.R

## Install Bioconductor packages
COPY ./misc/requirements-bioc.R .
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
   libfftw3-dev \
   gcc && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN Rscript -e 'requireNamespace("BiocManager"); BiocManager::install(ask=F);' \
&& Rscript requirements-bioc.R

## Install from GH the following
RUN installGithub.r neurogenomics/EWCE \
chris-mcginnis-ucsf/DoubletFinder \
theislab/kBET \
combiz/RANN.L1 \
NathanSkene/One2One \
hhoeflin/hdf5r \
mojaveazure/loomR \
cole-trapnell-lab/monocle3 \
neurogenomics/scFlowExample \
neurogenomics/scFlowData

## Install scFlow package
# Copy description
WORKDIR scFlow
ADD . .

# Install R package from source
RUN Rscript -e "remotes::install_local()"
RUN rm -rf *

## Check if scFlow installed
#RUN R -e 'library(scFlow)'
```

**Comment by crazy-max** [comment]
@Al-Murphy That's because you're using a [container to run any steps in a job](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer) (`container: almurphy/scfdev:latest`) where docker is not available. You must have a Docker engine running to use this action.

**Comment by Al-Murphy** [comment]
Hi @crazy-max, thank you very much for the quick response and my apologies for what is obviously a simple error! I am new to this are, by any chance do you know where I could find resources on building the image based on the docker file and then running the other action using that image? Apologies, I completely understand this is not related to this issue or any error with setup-buildx-action.

**Comment by crazy-max** [comment]
@Al-Murphy Ok so your idea is to use your Dockerfile as a container to run any steps in a job right? If it's the only purpose of this workflow then you should have a job to create this image and then use this image in another job. I'm not familiar with [container to run any steps in a job] and rlang but I think you could ask about your workflow in https://github.com/r-lib/actions.

**Comment by crazy-max** [comment]
If you want a simple workflow to build your Dockerfile, the following should work:

```yaml
name: R GitHub Actions

on:
  push:
    branches:
      - main
      - master
      - dev-am
  pull_request:
    branches:
      - main
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RGL_USE_NULL: TRUE
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          install-r: false
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Get R package version
        run: |
          version=$(grep Version DESCRIPTION | grep -o "[0-9.]\+")
          echo "packageVersion=${version}" >> $GITHUB_ENV
        shell: bash {0}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: almurphy/scfdev:${{ env.packageVersion }}
```

What I've changed:

* `tags: ${{ github.repository}}:${{ env.packageVersion }}`: not sure you want to push on `${{ github.repository}}` but `almurphy/scfdev` on Docker Hub? I guess?
* `if: github.event_name != 'pull_request'`: Don't login on pull request because secrets are not available.
* `push: ${{ github.event_name != 'pull_request' }}`: Don't push on pull request because secrets are not available.
