### ISSUE TITLE
Getting `docker: invalid reference format` annotation on runs using this action

### ISSUE THREAD

**Issue by dgholz** [docker/setup-buildx-action#96]
### Behaviour

Getting a warning annotation appearing on workflows that use `docker/setup-buildx-action`:
```
docker: invalid reference format. See 'docker run --help'.
```

#### Steps to reproduce this issue

1. `uses: docker/setup-buildx-action@v1` in your workflow
2. look at the action run summary page after triggering your workflow

#### Expected behaviour

Should not warn about a command run from within the action

#### Actual behaviour

Puzzling warning about a command I didn't run 

### Configuration

```yml
name: CICD
on:
  pull_request:
  push:
   branches: [master]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
```

### Logs

[setup-buildx-action.log](https://github.com/docker/setup-buildx-action/files/6732888/setup-buildx-action.log)

The warning annotation is coming from the end:
```
2021-06-29T10:52:22.9660083Z ##[group]BuildKit version
2021-06-29T10:52:23.0610726Z ##[warning]docker: invalid reference format.
See 'docker run --help'.
2021-06-29T10:52:23.0631583Z
```
